Repository KTC-Security-Circle/SC-system-frontend, pull requests merged in 2025-01, with the labels that each got.

#24 Chat機能のbakendとの接続
  .gitignore
  compose.yml
  src/Components/ChatDrawer.tsx
  src/Components/DynamicChatPage.tsx
  src/Components/parts/Chat/Chat.tsx
  src/Components/parts/Chat/DynamincChat.tsx
  src/Components/parts/Login.tsx
  src/Components/parts/Register.tsx
  src/Context/authSlice.ts
  src/app/Chat/[session_id]/page.tsx
  src/app/Chat/page.tsx
Labels: enhancement

#29 Feature/appbar adjust
  src/Components/AppbarButton.tsx
  src/Components/ChatAppbar.tsx
  src/Components/ChatPage.tsx
  src/Components/DynamicChatPage.tsx
  src/types/appbar.ts
Labels: fix

#31 Appbarを表示する
  src/Components/ChatAppbar.tsx
  src/Components/ChatPage.tsx
  src/Components/DynamicChatPage.tsx
  src/Components/parts/AppbarButton.tsx
  src/Components/parts/Chat/Chat.tsx
  src/Components/parts/Chat/DynamincChat.tsx
  src/Components/parts/ChatAppbar.tsx
Labels: enhancement, fix

#33 ボタンの重複とチャットのローディングを追加
  src/Components/parts/Chat/Chat.tsx
  src/Components/parts/Chat/DynamincChat.tsx
  src/Components/parts/ChatAppbar.tsx
Labels: fix

#35 Feature/addlogout
  src/Components/parts/ChatAppbar.tsx
  src/Context/authSlice.ts
Labels: fix

#37 Feature/fixlogout
  src/Components/parts/ChatAppbar.tsx
  src/Context/authSlice.ts
  src/types/appbar.ts
Labels: fix

#40 Feature/withicon
  public/ai_icon.png
  public/scsystemlogo.png
  src/Components/ChatPage.tsx
  src/Components/DynamicChatPage.tsx
  src/Components/parts/Chat/Chat.tsx
  src/Components/parts/Chat/DynamincChat.tsx
  src/Components/parts/ChatAppbar.tsx
  src/Components/parts/Login.tsx
  src/Components/parts/Register.tsx
  src/Context/authSlice.ts
  src/styles/image.module.css
Labels: fix

#42 Create .env.example(#41)
  .env.example
Labels: fix
