Repository KTC-Security-Circle/SC-system-frontend, pull requests merged in 2025-02, with the labels that each got.

#48 Feature/calendar
  compose.yml
  package-lock.json
  package.json
  src/Components/AdminPageComponent.tsx
  src/Components/Calendar/calendar.tsx
  src/app/Admin/ScheduleManagement/page.tsx
Labels: enhancement

#39 Feature/school markdown
  package-lock.json
  package.json
  src/Components/Editor.tsx
  src/Components/MarkdownNavgation.tsx
  src/Components/MarkdownPreview.tsx
  src/Components/NavigateBackButton.tsx
  src/Components/markdown.css
  src/app/Admin/School/page.tsx
  src/app/Information/fetchmd.ts
  src/app/Information/page.tsx
  src/app/Information/test.md
  src/app/Markdown/page.tsx
  src/types/navigateback.ts
Labels: enhancement, fix

#52 fix 専攻の登録を削除(#51)
  src/Components/parts/Register.tsx
Labels: fix

#50 ランディングページの作成
  .github/workflows/azure-static-web-apps-black-wave-044ddf100.yml
  next.config.mjs
  package-lock.json
  package.json
  src/Components/LandingPageComponent.tsx
  src/Components/parts/LP/FeaturePart.tsx
  src/Components/parts/LP/Footer.tsx
  src/Components/parts/LP/UseButton.tsx
  src/app/Home/page.tsx
  src/app/page.tsx
Labels: enhancement, fix
